# Server Configuration
quarkus:
  application:
    name: gdp-dataserving-server
  http:
    port: 8082
    cors:
      ~: true
      origins: "*"
      methods: "GET,POST,PUT,DELETE,OPTIONS"
      headers: "*"

  # OIDC Configuration
  oidc:
    auth-server-url: ${OIDC_AUTH_SERVER_URL:https://your-keycloak-server/auth/realms/your-realm}
    client-id: ${OIDC_CLIENT_ID:gdp-dataserving}
    credentials:
      secret: ${OIDC_CLIENT_SECRET:your-client-secret}
    application-type: service
    token:
      issuer: ${OIDC_TOKEN_ISSUER:https://your-keycloak-server/auth/realms/your-realm}
      audience: ${OIDC_TOKEN_AUDIENCE:gdp-dataserving}

  # Security Configuration
  security:
    jaxrs:
      deny-unannotated-endpoints: false

  # Database Configuration
  datasource:
    db-kind: postgresql
    username: ${DB_USERNAME:gdp_user}
    password: ${DB_PASSWORD:gdp_password}
    jdbc:
      url: ${DB_URL:jdbc:postgresql://localhost:5432/gdp_dataserving}
      max-size: 16
      min-size: 2

  # Hibernate Configuration
  hibernate-orm:
    database:
      generation: none
    log:
      sql: false
      format-sql: true
    dialect: org.hibernate.dialect.PostgreSQLDialect

  # Flyway Configuration
  flyway:
    migrate-at-start: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0

  # GraphQL Configuration
  smallrye-graphql:
    ui:
      enable: true
    root-path: /graphql
    events:
      enabled: true

  # Logging Configuration
  log:
    level: INFO
    category:
      "com.sc.gdp": DEBUG
      "io.quarkus.oidc": DEBUG

# Development Profile
"%dev":
  quarkus:
    # Development Database Configuration (H2 for easy setup)
    datasource:
      db-kind: h2
      username: sa
      password: 
      jdbc:
        url: jdbc:h2:mem:gdp_dev;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        max-size: 8
        min-size: 1
    
    # Hibernate Configuration for Development
    hibernate-orm:
      database:
        generation: drop-and-create
      log:
        sql: true
        format-sql: true
    
    # Flyway Configuration for Development
    flyway:
      migrate-at-start: false  # Let Hibernate handle schema in dev mode
    
    oidc:
      auth-server-url: http://localhost:8180/auth/realms/quarkus
      client-id: backend-service
      credentials:
        secret: secret
    log:
      level: DEBUG

# Test Profile
"%test":
  quarkus:
    oidc:
      auth-server-url: http://localhost:8180/auth/realms/quarkus
      client-id: backend-service
      credentials:
        secret: secret